spring.application.name=maven-demo
server.port=5050
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/retailflow
spring.datasource.username=root
spring.datasource.password=root